services:
  webapp:
    container_name: unipe-pyspark-jupyter
    build: .
    command: start.sh jupyter lab --LabApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - ${NOTEBOOKS_PATH}:/home/jovyan/work/notebooks/
      - ${DATA_PATH}:/home/jovyan/work/datalake/
    environment:
      PYARROW_IGNORE_TIMEZONE: 1
